version: '2'

services:
  deploy:
    image: zetaron/hook-deployment-worker:1.0.0
    volumes:
      - secrets:/var/secrets
      - cache:/var/cache/deployment

volumes:
  secrets:
    external:
      name: $SECRETS_VOLUME_NAME
  cache:
    external:
      name: $DEPLOYMENT_CACHE_VOLUME_NAME
