version: '2.1'

services:
  deploy:
    image: zetaron/github-deployment-worker:1.0.0
    volumes:
      - secrets:/var/cache/secrets
      - cache:/var/cache/deployment

volumes:
  secrets:
    external:
      name: ${SECRET_VOLUME_NAME:-cashier-production-secrets}
  cache:
    external:
      name: $DEPLOYMENT_CACHE_VOLUME_NAME
