#!/bin/sh

# Orignially found at: https://github.com/docker/docker/issues/13490#issuecomment-191836233
# Converted to POSIX shell

if [ -d "/var/cache/secrets" ]
then
    tmpfile="$(mktemp)"

    for file in /var/cache/secrets/*
    do
        if [ -f "$file" ]
        then
            file_contents=$(cat "$file")
            filename=$(basename "$file")
            underscored_filename=$(printf '%s' "$filename" | tr '-' '_')
            capitalized_filename=$(echo "$underscored_filename" | tr "[:lower:]" "[:upper:]")

            echo "export $capitalized_filename=$file_contents" >> "$tmpfile"
        fi
    done

    # shellcheck source=/dev/null
    . "$tmpfile"

    rm -f "$tmpfile"
fi

exec "$@"
