#!/bin/sh
set -ex

DEPLOYMENT_ENVIRONMENT=${DEPLOYMENT_ENVIRONMENT:-production}
DNSNAME=${CASHIER_DNSNAME:-cashier.zetaron.de}
CASHIER_VERSION=${CASHIER_VERSION:-1.0.0}
CASHIER_REPLICAS=${CASHIER_REPLICAS:-1}
SCHEDULE_ONTO_NODE=${SCHEDULE_ONTO_NODE:-"cluster-node-1"}

if [ "$(docker volume ls -q | grep "cashier-secrets")" == "" ]
then
    docker volume create \
           --name cashier-secrets
fi

if [ "$(docker service ls -q --filter name=cashier)" == "" ]
then
    docker service create \
           --name cashier \
           --network frontends \
           --mount type=volume,source=cashier-secrets,destination=/var/cache/secrets \
           --replicas $CASHIER_REPLICAS \
           --label ingress=true \
           --label ingress.dnsname=$DNSNAME \
           --label ingress.targetport=80 \
           --constraint "node.hostname == ${SCHEDULE_ONTO_NODE}" \
           zetaron/cashier:$CASHIER_VERSION
else
    docker service update \
           --image zetaron/cashier:$CASHIER_VERSION \
           --label-add ingress.dnsname=$DNSNAME \
           --replicas $CASHIER_REPLICAS \
           cashier
fi
