#!/bin/sh

while true; do
    read -p "Do you wish to set the CLIENT_ID? [yn]" yn_set_client_id
    case $yn_set_client_id in
        [Yy]* )
            read -p "CLIENT_ID: " client_id
            echo $client_id | docker run --rm -i -v cashier-secrets:/var/cache/secrets alpine:3.4 dd of=/var/cache/secrets/CLIENT_ID
            break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done

while true; do
    read -p "Do you wish to set the CLIENT_SECRET? [yn]" yn_set_client_secret
    case $yn_set_client_secret in
        [Yy]* )
            read -p "CLIENT_SECRET: " client_secret
            echo $client_secret | docker run --rm -i -v cashier-secrets:/var/cache/secrets alpine:3.4 dd of=/var/cache/secrets/CLIENT_SECRET
            break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
